server:
  port: 8080
spring:
  main:
    web-application-type: none
    banner-mode: false
  application:
    name: AIgenie
  ai:
    openai:
      api-key: sk-
      base-url: https://api.siliconflow.cn/v1
      chat:
        options:
          model: Pro/deepseek-ai/DeepSeek-V3
          temperature: 0.7
          max-tokens: 2000
logging:
  level:
    root: INFO
    com.aIgenie: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.web.client: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: ./logs/aigenie.log
aigenie:
  system-prompt: 你是一个有用的AI助手，名为'AIgenie'。请简洁明了地回答用户的问题。
  chat-history-limit: 10
  use-custom-client: true
  theme: 浅色
  docking-enabled: true
shell:
  interactive:
    enabled: false
